chore: Release 2025-04-18 10:59:22 (#536)
This PR was opened by the [Changesets
release](https://github.com/changesets/action) GitHub action. When
you're ready to do a release, you can merge this and the packages will
be published to npm automatically. If you're not ready to do a release
yet, that's fine, whenever you add more changesets to main, this PR will
be updated.


# Releases
## @lynx-js/web-core@0.12.0

### Minor Changes

- feat: improve compatibility for chrome 108 & support linear-gradient
for nested x-text
([#590](https://github.com/lynx-family/lynx-stack/pull/590))

    **This is a breaking change**

    -   Please upgrade your `@lynx-js/web-elements` to >=0.6.0
    -   Please upgrade your `@lynx-js/web-core` to >=0.12.0
    -   The compiled lynx template json won't be impacted.

On chrome 108, the `-webkit-background-clip:text` cannot be computed by
a `var(--css-var-value-text)`

    Therefore we move the logic into style transformation logic.

    Now the following status is supported

        <text style="color:linear-gradient()">
          <text>
          <text>
        </text>

### Patch Changes

- feat: allow user to implement custom template load function
([#587](https://github.com/lynx-family/lynx-stack/pull/587))

    ```js
    lynxView.customTemplateLoader = (url) => {
      return (await (await fetch(url, {
        method: 'GET',
      })).json());
    };
    ```

- feat: support mts event with target methods
([#564](https://github.com/lynx-family/lynx-stack/pull/564))

After this commit, developers are allowed to invoke
`event.target.setStyleProperty` in mts handler

- fix: crash on removing a id attribute
([#582](https://github.com/lynx-family/lynx-stack/pull/582))

- Updated dependencies
\[[`f1ca29b`](https://github.com/lynx-family/lynx-stack/commit/f1ca29bd766377dd46583f15e1e75bca447699cd)]:
    -   @lynx-js/web-worker-runtime@0.12.0
    -   @lynx-js/web-constants@0.12.0
    -   @lynx-js/web-worker-rpc@0.12.0

## @lynx-js/web-elements@0.6.0

### Minor Changes

- fix: When list-type is not specified, it is treated as single
formatting. ([#535](https://github.com/lynx-family/lynx-stack/pull/535))

- feat: improve compatibility for chrome 108 & support linear-gradient
for nested x-text
([#590](https://github.com/lynx-family/lynx-stack/pull/590))

    **This is a breaking change**

    -   Please upgrade your `@lynx-js/web-elements` to >=0.6.0
    -   Please upgrade your `@lynx-js/web-core` to >=0.12.0
    -   The compiled lynx template json won't be impacted.

On chrome 108, the `-webkit-background-clip:text` cannot be computed by
a `var(--css-var-value-text)`

    Therefore we move the logic into style transformation logic.

    Now the following status is supported

        <text style="color:linear-gradient()">
          <text>
          <text>
        </text>

### Patch Changes

- feat: fully support MTS
([#569](https://github.com/lynx-family/lynx-stack/pull/569))

    Now use support the following usage

    -   mainthread event
    -   mainthread ref
    -   runOnMainThread/runOnBackground
    -   ref.current.xx

- feat: support `layoutchange` event for x-overlay-ng
([#519](https://github.com/lynx-family/lynx-stack/pull/519))

- fix: position:fixed not work in scroll-view
([#580](https://github.com/lynx-family/lynx-stack/pull/580))

- fix: x-list may cause error: 'Resizeobserver loop completed with
undelivered notifications'.
([#541](https://github.com/lynx-family/lynx-stack/pull/541))

- fix: refactor foldview slot offset logic
([#575](https://github.com/lynx-family/lynx-stack/pull/575))

- fix: improve x-foldview-ng
([#513](https://github.com/lynx-family/lynx-stack/pull/513))

    -   support fling for touch event driven scrolling
- allow the height of `x-foldview-slot-ng` + `x-foldview-toolbar-ng` >
`x-foldview-ng`
- do not prevent horizontal gesture. After this commit we only allow one
direction gesture for one touch (start -> end)

- feat: add list with waterfall
([#331](https://github.com/lynx-family/lynx-stack/pull/331))

## @lynx-js/web-style-transformer@0.3.0

### Minor Changes

- feat: improve compatibility for chrome 108 & support linear-gradient
for nested x-text
([#590](https://github.com/lynx-family/lynx-stack/pull/590))

    **This is a breaking change**

    -   Please upgrade your `@lynx-js/web-elements` to >=0.6.0
    -   Please upgrade your `@lynx-js/web-core` to >=0.12.0
    -   The compiled lynx template json won't be impacted.

On chrome 108, the `-webkit-background-clip:text` cannot be computed by
a `var(--css-var-value-text)`

    Therefore we move the logic into style transformation logic.

    Now the following status is supported

        <text style="color:linear-gradient()">
          <text>
          <text>
        </text>

## @lynx-js/react@0.106.5

### Patch Changes

- Fix `lynx.loadLazyBundle` is not a function
([#568](https://github.com/lynx-family/lynx-stack/pull/568))

- fix: flushDelayedLifecycleEvents stack overflow error
([#540](https://github.com/lynx-family/lynx-stack/pull/540))

## @lynx-js/rspeedy@0.9.2

### Patch Changes

- Support cli option `--no-env` to disable loading of .env files
([#483](https://github.com/lynx-family/lynx-stack/pull/483))

- Bump Rsbuild v1.3.8 with Rspack v1.3.5.
([#579](https://github.com/lynx-family/lynx-stack/pull/579))

## @lynx-js/react-rsbuild-plugin@0.9.7

### Patch Changes

- Support overriding SWC configuration.
([#563](https://github.com/lynx-family/lynx-stack/pull/563))

Now you can override configuration like `useDefineForClassFields` using
`tools.swc`.

    ```js
    import { defineConfig } from "@lynx-js/rspeedy";

    export default defineConfig({
      tools: {
        swc: {
          jsc: {
            transform: {
              useDefineForClassFields: true,
            },
          },
        },
      },
    });
    ```

- Updated dependencies
\[[`f1ca29b`](https://github.com/lynx-family/lynx-stack/commit/f1ca29bd766377dd46583f15e1e75bca447699cd)]:
    -   @lynx-js/react-webpack-plugin@0.6.11
    -   @lynx-js/react-alias-rsbuild-plugin@0.9.7
    -   @lynx-js/react-refresh-webpack-plugin@0.3.2
    -   @lynx-js/web-webpack-plugin@0.6.5

## @lynx-js/web-constants@0.12.0

### Patch Changes

- feat: fully support MTS
([#569](https://github.com/lynx-family/lynx-stack/pull/569))

    Now use support the following usage

    -   mainthread event
    -   mainthread ref
    -   runOnMainThread/runOnBackground
    -   ref.current.xx

-   Updated dependencies \[]:
    -   @lynx-js/web-worker-rpc@0.12.0

## @lynx-js/web-explorer@0.0.5

### Patch Changes

- fix: create a new lynx-view for lynxjs.org
([#566](https://github.com/lynx-family/lynx-stack/pull/566))

- fix: blank screen issue for 0.0.4
([#543](https://github.com/lynx-family/lynx-stack/pull/543))

## @lynx-js/web-mainthread-apis@0.12.0

### Patch Changes

- feat: fully support MTS
([#569](https://github.com/lynx-family/lynx-stack/pull/569))

    Now use support the following usage

    -   mainthread event
    -   mainthread ref
    -   runOnMainThread/runOnBackground
    -   ref.current.xx

- feat: support mts event with target methods
([#564](https://github.com/lynx-family/lynx-stack/pull/564))

After this commit, developers are allowed to invoke
`event.target.setStyleProperty` in mts handler

- fix: crash on removing a id attribute
([#582](https://github.com/lynx-family/lynx-stack/pull/582))

- Updated dependencies
\[[`f1ca29b`](https://github.com/lynx-family/lynx-stack/commit/f1ca29bd766377dd46583f15e1e75bca447699cd),
[`7edf478`](https://github.com/lynx-family/lynx-stack/commit/7edf478410cb57eeedc18aac6f5d3950b16c7fa8)]:
    -   @lynx-js/web-constants@0.12.0
    -   @lynx-js/web-style-transformer@0.3.0

## @lynx-js/web-worker-runtime@0.12.0

### Patch Changes

- feat: fully support MTS
([#569](https://github.com/lynx-family/lynx-stack/pull/569))

    Now use support the following usage

    -   mainthread event
    -   mainthread ref
    -   runOnMainThread/runOnBackground
    -   ref.current.xx

- Updated dependencies
\[[`f1ca29b`](https://github.com/lynx-family/lynx-stack/commit/f1ca29bd766377dd46583f15e1e75bca447699cd),
[`8ca9fcb`](https://github.com/lynx-family/lynx-stack/commit/8ca9fcbbc86b0f0ac05ee4319876cdd5dd08d668),
[`efe6fd7`](https://github.com/lynx-family/lynx-stack/commit/efe6fd7de8a3d8119ea550f4d4e939d1fbfee4f0)]:
    -   @lynx-js/web-mainthread-apis@0.12.0
    -   @lynx-js/web-constants@0.12.0
    -   @lynx-js/web-worker-rpc@0.12.0

## @lynx-js/react-webpack-plugin@0.6.11

### Patch Changes

- feat: fully support MTS
([#569](https://github.com/lynx-family/lynx-stack/pull/569))

    Now use support the following usage

    -   mainthread event
    -   mainthread ref
    -   runOnMainThread/runOnBackground
    -   ref.current.xx

## @lynx-js/web-webpack-plugin@0.6.5

### Patch Changes

- Updated dependencies
\[[`7edf478`](https://github.com/lynx-family/lynx-stack/commit/7edf478410cb57eeedc18aac6f5d3950b16c7fa8)]:
    -   @lynx-js/web-style-transformer@0.3.0

## create-rspeedy@0.9.2



## @lynx-js/react-alias-rsbuild-plugin@0.9.7



## upgrade-rspeedy@0.9.2



## @lynx-js/web-worker-rpc@0.12.0

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>